### ISSUE TITLE
[Header/Footer/Home] - Create layout 2.0

### ISSUE THREAD

**Issue by LuisKrotz** [almeidamarco/marco-almeida-portfolio#14]

**Comment by almeidamarco** [comment]
@LuisKrotz, sobre o object-position das imagens na home:

### Coza 
object-position: top right;
### Melissa Insider 
object-position: top left;
### Melissa
object-position: top center;

**Comment by almeidamarco** [comment]
@LuisKrotz, definição das alturas da viewport desktop na home:

- 2560 x 1440px
- 1920 x 1080px
- 1680 x 1050px
- 1440 x 900px
- 1366 x 768px
- 1280 x 800px
- 1024 x 768px

> Fonte: principais resoluções de acesso ao meu site desde 2014.

![top-10-screen-resolution](https://user-images.githubusercontent.com/14944962/83947255-52b5fb80-a7ec-11ea-831b-d748ca5006c4.png)
