### ISSUE TITLE
[Review] - Interactions

### ISSUE THREAD

**Issue by almeidamarco** [almeidamarco/marco-almeida-portfolio#8]
Review date: 
May 14th

NAVIGATION
---
- [x] Quando volto de um case pra index, a “logo” perde a posição fixa na rolagem
- [x] Quando volto da página de erro pra index, os itens do header não reaparecem
- [x] Transição entre páginas: quando estou no final do about ou do case e volto pra home, o scroll se mantém no final. Podemos voltar o scroll pro topo nessas trocas, aplicando troca de opacidade de uma página pra outra pra suavizar a transição?

CLICK & HOVER
---
- [x] Revisar mouse over em todos os elementos de texto com link para: troca de opacidade de 100% para 50%. Exceto no “Get back on track” na página de erro, que é ao contrário. E exceto para os cases na home, também. Padronizar transition para: 0.25s ease;
- [x] No mouse over dos projetos na index, trocar o cursor para a imagem que está [nessa pasta](https://drive.google.com/drive/u/0/folders/1QddLbCBEt7Urrkizu-7UgGCeEkRUMwIr). Exportei elas x2 por causa dos monitores retina
- [x] [TBD] Revisar a área de clique dos elementos de texto, pois algumas estão enormes

PARALLAX
---
- [x] [TBD - Almeida] Revisar o parallax

LOADER
---
- [x] Revisar a animação do loader de acordo com a imagem em anexo. O vídeo da animação está [nessa pasta](https://drive.google.com/drive/u/0/folders/1UifLBXTeHLaZL4Gzzj0TAPTflRbdBksX) do Drive

![MA - Personal Website - Loader Animation](https://user-images.githubusercontent.com/14944962/82006069-5ca96c00-963d-11ea-812f-dc8bab321879.jpg)

**Comment by LuisKrotz** [comment]
@almeidamarco 

No item, como comentamos, vou adicionar um fade-in na entrada.
Transição entre páginas: quando estou no final do about ou do case e volto pra home, o scroll se mantém no final. Podemos voltar o scroll pro topo nessas trocas, aplicando troca de opacidade de uma página pra outra pra suavizar a transição?

**Comment by almeidamarco** [comment]
@LuisKrotz 

Algumas referências:
- Outra alternativa de animação para o loader - https://justified.studio/
- Transição entre páginas e entrada dos elementos - https://basicagency.com/
- Parallax: podemos testar isso - quando o case aparece centralizado no viewport, o type assume a posição original. Mas texto e imagem chegam em tempos diferentes no viewport ao saírem de pontos diferentes antes disso - https://parall.ax/

**Comment by almeidamarco** [comment]
@LuisKrotz 

Reabrindo a issue só por conta de um item:
- No mouse over dos projetos na index, trocar o cursor para a imagem que está nessa pasta. Exportei elas x2 por causa dos monitores retina

Em @1280 basta chamar a imagem 1 ao invés da 2, pois está a mesma para ambos.

![Screen Shot 2020-05-17 at 19 52 41](https://user-images.githubusercontent.com/14944962/82162095-476c5180-9878-11ea-8fe0-dfecd9d65f1d.png)

**Comment by almeidamarco** [comment]
@LuisKrotz

Reabrindo a issue por conta do mouse over dos projetos:
- Agora ficou a imagem 1 para ambos os breakpoints e não é isso que queremos. Precisamos chamar a imagem `explore1.png` para @1280 e a imagem `explore2.png` para @2560

Outra coisa sobre esse ponto.
- Conseguimos melhorar o tracking do cursor? Ele está bom, mas não está perfeito. Ilustrando abaixo o que quis dizer, e também uma referência onde ele funciona perfeitamente.

📁 [cursor-hover.zip](https://github.com/almeidamarco/marco-almeida-portfolio/files/4645548/cursor-hover.zip)
🔗 https://hanzo.es/
