### ISSUE TITLE
[Review] - Interface

### ISSUE THREAD

**Issue by almeidamarco** [almeidamarco/marco-almeida-portfolio#9]
Review date: 
May 12th – May 15th

INDEX
---
@2560 a @1440

- [x] Revisar as margens entre itens na lista “Featured on” para 8px

@2560 a @800

- [x] Usar o mesmo margin-top do “Marco Almeida” para o margin-bottom da lista de social links e também do “Back to top"

@1920 a @1440

- [x] Revisar o width do parágrafo inicial (home-content) para deixar na mesma largura da imagem dos cases

@1280

- [x] Revisar o width da imagem dos cases para ter a mesma do parágrafo inicial, pois está menor
- [x] Revisar o width do .home-project-title que está maior do que no InVision 

@1280 a @320

- [x] Revisar o height do header (.nav) que muda de 128px para 80px em @1280 pra baixo. Revisar a margem abaixo dele com o InVision
- [x] Revisar o letter-spacing dos textos para o valor negativo que está no InVision

@1024

- [x] Revisar o letter-spacing do .home-project-title que está maior do que no InVision

ABOUT + 404
---
@All

- [x] Revisar técnica de posição/largura/margens do about-list-text-number e do about-list-text-description porque estão variando de um item pro outro, e também não estão batendo com o que está no InVision

@2560

- [x] Revisar font-size do about-list-item com o que está no InVision, nessa resolução o tamanho é maior

@1440

- [x] Revisar o width do parágrafo inicial (about-title) pois está maior do que no InVision

@1280

- [x] Revisar o width dos itens para ter a mesma do parágrafo inicial, pois está menor, como aconteceu na home

@1280 a @320

- [x] Revisar font-size do about-list-item com o que está no InVision, de @1280 para baixo o font-size é menor

CASES
---
@All

- [x] Remover o margin-bottom da última imagem/vídeo de cada case, pois essa é desnecessária
- [x] Revisar o estilo tipográfico e o alinhamento vertical do projects-aside, pois não está batendo com o InVision
- [x] Revisar distâncias entre blocos de texto e imagens, algumas estão menores e outras maiores do que no InVision
- [x] Revisar estilo tipográfico do texto Abduzeedo em Coza e Sandu Publishing em Melissa Insider, na parte de Recognition, pois ficaram diferentes

@2560 a @1680

- [x] Revisar o width da área principal de texto (central-text-area) pois está menor do que no InVision

**Comment by almeidamarco** [comment]
@LuisKrotz 

Reabrindo a issue por conta dos itens acima que ainda não estão ok.

INDEX
---
@2560 a @1440

- Revisar o width do parágrafo inicial (home-content) para deixar na mesma largura das imagens dos projetos abaixo. Entre @1680 e @1440 o max-width está maior, e entre @2560 e @1920 está menor.

![Screen Shot 2020-05-17 at 20 02 09](https://user-images.githubusercontent.com/14944962/82162307-e5145080-9879-11ea-8ef5-b75a94c75d05.png)

@1024

- Revisar o letter-spacing do .home-project-title que está maior do que no InVision. O valor correto é de -6px.

![Screen Shot 2020-05-17 at 20 08 25](https://user-images.githubusercontent.com/14944962/82162398-7edbfd80-987a-11ea-8877-bbbacaddfdee.png)

**Comment by almeidamarco** [comment]
Alguns itens novos:

ABOUT
---
@320
- [ ] O texto ficou colado na imagem. Podemos usar a mesma distância do @414.

![Screen Shot 2020-05-17 at 20 21 18](https://user-images.githubusercontent.com/14944962/82162593-11c96780-987c-11ea-967f-01f56ae283d4.png)

CASES
---
@1680 a @320
- [ ] Revisar o padding-top e padding-bottom dos itens do footer para que fiquem idênticos. Na maioria dos breakpoints o padding-top está bem maior do que o bottom.

![Screen Shot 2020-05-17 at 20 18 43](https://user-images.githubusercontent.com/14944962/82162623-594ff380-987c-11ea-8ccb-ced16d57e371.png)

**Comment by LuisKrotz** [comment]
![Screen Shot 2020-05-17 at 10 47 09 PM](https://user-images.githubusercontent.com/18265646/82167543-91fac780-9892-11ea-8f62-826145d240e1.png)
![Screen Shot 2020-05-17 at 10 48 35 PM](https://user-images.githubusercontent.com/18265646/82167560-9aeb9900-9892-11ea-8a5d-fbbfe5733eb2.png)

![Screen Shot 2020-05-17 at 10 47 30 PM](https://user-images.githubusercontent.com/18265646/82167547-92935e00-9892-11ea-81cf-f153da810ec0.png)
![Uploading Screen Shot 2020-05-17 at 10.50.07 PM.png…]()

![Screen Shot 2020-05-17 at 10 47 52 PM](https://user-images.githubuserconte
![Screen Shot 2020-05-17 at 10 49 34 PM](https://user-images.githubusercontent.com/18265646/82167562-9cb55c80-9892-11ea-9982-b9c48ba3aa52.png)
nt.com/18265646/82167549-932bf480-9892-11ea-96a2-43b76869a9b0.png)
![Screen Shot 2020-05-17 at 10 48 06 PM](https://user-images.githubusercontent.com/18265646/82167550-93c48b00-9892-11ea-8ae2-45c9d6c12020.png)
![Screen Shot 2020-05-17 at 10 48 25 PM](https://user-images.githubusercontent.com/18265646/82167552-945d2180-9892-11ea-8706-c1ed7b0664ab.png)

![Screen Shot 2020-05-17 at 10 46 51 PM](https://user-images.githubusercontent.com/18265646/82167539-90c99a80-9892-11ea-9881-fd2e241eb076.png)
![Screen Shot 2020-05-17 at 10 46 04 PM](https://user-images.githubusercontent.com/18265646/82167535-8c04e680-9892-11ea-9a60-05c36bd7a13f.png)


Alinhamento optico acima. 
O 404 nao percebi que era pra ser centralizado. Refiz a página. 

Tudo no staging. Subi as outras 2 todos também.

**Comment by almeidamarco** [comment]
@LuisKrotz boa! revisei os itens acima e quase todos estão ok. Só um ainda não, que comentei abaixo com outros dois novos.

INDEX
---
@1024
- [ ] Ajustar o bottom do .home-project-title para 72px como no InVision, pois está menor.

CASES
---
@1680 a @320
Em Melissa Insider e Brazilian Leather esse item ainda não está ok.

- [ ] Revisar o padding-top e padding-bottom dos itens do footer para que fiquem idênticos. Na maioria dos breakpoints o padding-top está bem maior do que o bottom.

@2560 a @320

- [ ] A imagem abaixo ficou cortada na base. Era pra ter o mesmo tamanho da imagem à esquerda.

<img width="1392" alt="Screen Shot 2020-05-18 at 13 46 00" src="https://user-images.githubusercontent.com/14944962/82239192-c6ac6480-990e-11ea-99fc-19cdbee68e3d.png">
